### ISSUE TITLE
Add context to the callback functions

### ISSUE THREAD

**Issue by dawoun** [tlsa/libcyaml#101]
Currently, the logging and memory allocation callback functions do not provide a context variable.
It would be helpful to have a context in the callback to allow for easier implementation.

**Comment by tlsa** [comment]
Yes, good idea.  I'll do this soon. :smile_cat:

**Comment by tlsa** [comment]
Actually, the allocation function does already have this:

* [`ctx` param to `cyaml_mem_fn_t`](https://github.com/tlsa/libcyaml/blob/b52e54a61a65bda4a9cd83b960e5aa8a311a9fe0/include/cyaml/cyaml.h#L1337)
* [`mem_ctx` in `cyaml_config_t`](https://github.com/tlsa/libcyaml/blob/b52e54a61a65bda4a9cd83b960e5aa8a311a9fe0/include/cyaml/cyaml.h#L1385)

**Comment by tlsa** [comment]
I can add a `log_ctx` member to the CYAML config structure, `cyaml_config_t`, and send it out as a parameter to `cyaml_log_fn_t` functions.

**Comment by dawoun** [comment]
> Actually, the allocation function does already have this:
> 

Oh, sorry, missed that. I was actually looking for it in the logging function.

> I can add a `log_ctx` member to the CYAML config structure, `cyaml_config_t`, and send it out as a parameter to `cyaml_log_fn_t` functions.

That would work, thanks ;->

**Comment by tlsa** [comment]
Please have a look at https://github.com/tlsa/libcyaml/pull/102 and let me know if it works for you!

**Comment by dawoun** [comment]
> Please have a look at #102 and let me know if it works for you!

Yep, it works.
Thanks for the very quick turnaround!

**Comment by tlsa** [comment]
Thanks, merged! :tada:
