### ISSUE TITLE
Test failure with libyaml 0.2.5

### ISSUE THREAD

**Issue by mbakke** [tlsa/libcyaml#134]
Hi, after updating to libyaml 0.2.5, this test started failing:

```
================================================================================
TEST: Save tests: ptr sequence with null values
================================================================================
  FAIL: test_save_sequence_null_values_int (Bad data:
EXPECTED (38):

---
- 7
- 6
- 5
- 
- 3
- 2
- 
- 0
...


GOT (36):

---
- 7
- 6
- 5
-
- 3
- 2
-
- 0
...

)
```

Any idea what's going on here?

**Comment by perlpunk** [comment]
That's probably because of https://github.com/yaml/libyaml/pull/186

Trailing spaces for empty nodes are not emitted anymore. If you open the output in an editor you should see the trailing spaces.

**Comment by tlsa** [comment]
@mbakke Thanks for the report!

@perlpunk Yeah, looks like that's the reason, thanks!

**Comment by tlsa** [comment]
@mbakke Please could you test with this branch: [tlsa/libyaml-0.2.5-test-fix](https://github.com/tlsa/libcyaml/commits/tlsa/libyaml-0.2.5-test-fix)?

**Comment by mbakke** [comment]
@tlsa I can confirm that https://github.com/tlsa/libcyaml/commit/0e947264b947f51f7ea785068637c4bfce5d4171 works, thanks!

**Comment by tlsa** [comment]
@mbakke Thanks, the fix has been merged.
