### ISSUE TITLE
fails to load yaml if fields schema is empty

### ISSUE THREAD

**Issue by alex-tee** [tlsa/libcyaml#136]
I can save into a yaml with no errors even when a fields schema is empty (only has `CYAML_FIELD_END`) but it fails to load.

I temporarily removed the only thing that I had in this particular schema because I moved it somewhere else and I thought this would still work without changing the rest of the code or removing the schema completely (I plan to add things to it in the future). Is this supposed to be supported or should users never do this?

**Comment by tlsa** [comment]
Could you test with https://github.com/tlsa/libcyaml/pull/137 please?

**Comment by alex-tee** [comment]
@tlsa that worked, thanks!

**Comment by tlsa** [comment]
Thanks, merged!
