### ISSUE TITLE
-lyaml flag provided by pkg-config conflicts with the one provided by libyaml, a different library

### ISSUE THREAD

**Issue by fpesari** [tlsa/libcyaml#142]
Hello,

this is `libcyaml`'s pkg-config:

```
prefix=PREFIX
exec_prefix=${prefix}
libdir=${exec_prefix}/LIBDIR
includedir=${prefix}/INCLUDEDIR

Name: libcyaml
Description: Schema-based YAML parsing and serialisation
Version: VERSION
Libs: -L${libdir} -lcyaml -lyaml
Cflags: -I${includedir}
```
this is `libyaml`'s pkg-config:

```
prefix=@prefix@
exec_prefix=@exec_prefix@
includedir=@includedir@
libdir=@libdir@

Name: LibYAML
Description: Library to parse and emit YAML
Version: @PACKAGE_VERSION@
Cflags: -I${includedir}
Libs: -L${libdir} -lyaml
```

As you can see, they both provide the `-lyaml` linker flag. This causes problems when building some programs, as they might require `libyaml` even when `libcyaml` is exclusively used (it happened to me recently on openSUSE)!

It'd be best if `-lcyaml` were the only linker flag provided by pkg-config.

**Comment by tlsa** [comment]
> as they might require `libyaml` even when `libcyaml` is exclusively used

LibYAML is a dependency of LibCYAML, so you can't use LibCYAML exclusively.

**Comment by fpesari** [comment]
Whoops! My apologies, closing this issue.
