### ISSUE TITLE
Can't `make` on Windows

### ISSUE THREAD

**Issue by eastman-bechamo** [tlsa/libcyaml#160]
I'm using GnuWin32 Make on Windows to try to compile this library, but every time I run `make` or `make install VARIANT=release` I get an error that says `The syntax of the command is incorrect`.

I haven't changed anything in the Makefile or the repository. I'd be happy to provide additional information upon request.

Thanks!

**Comment by tlsa** [comment]
I don't have Windows myself.

Please update to the latest `main` branch (commit `6f2ad8b1278853e0cf2ee9a4ae8bc3179dd532ec`), and build with:

```bash
make Q=
```

That should indicate what command it is saying has incorrect syntax.  And please copy the whole output into a message.

Thanks for the report!
