### ISSUE TITLE
Fails to make on MacOS 10.15.7 Catalina

### ISSUE THREAD

**Issue by machinechat** [tlsa/libcyaml#163]
iMac27:~/downloads/libcyaml-main-2 % make
cc -o build/debug/libcyaml.so.1 build/debug/shared/src/mem.o build/debug/shared/src/free.o build/debug/shared/src/load.o build/debug/shared/src/save.o build/debug/shared/src/util.o build/debug/shared/src/utf8.o -L/usr/local/lib/ -lyaml  -Wl,-soname=libcyaml.so.1 -shared
ld: unknown option: -soname=libcyaml.so.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/debug/libcyaml.so.1] Error 1

**Comment by tlsa** [comment]
Seems to be a difference in linkers on macs.

Try changing this line in the Makefile:

```make
LDFLAGS_SHARED += -Wl,-soname=$(LIB_SH_MAJ) -shared
```

to

```make
LDFLAGS_SHARED += -Wl,-install_name=$(LIB_SH_MAJ) -shared
```

And let me know if it helps!

**Comment by tlsa** [comment]
Mac builds should work now, from `main` branch.  CI jobs have been added to build and test on macos too.
