### ISSUE TITLE
Example Planner does not compile

### ISSUE THREAD

**Issue by CameronLovesCoffee** [tlsa/libcyaml#166]
Ubuntu 18.04

C++ 17 - set(CMAKE_CXX_STANDARD 17)

line 264:
        CYAML_FIELD_SEQUENCE(
                "depends", CYAML_FLAG_POINTER | CYAML_FLAG_OPTIONAL,
                struct task, depends,
                &string_ptr_schema, 0, CYAML_UNLIMITED),

error message:
error: designator order for field ‘cyaml_schema_field::data_offset’ does not match declaration order in ‘const cyaml_schema_field_t’ {aka ‘const cyaml_schema_field’}

cause:
the CYAML_FIELD_SEQUENCE declares the struct in the wrong order

fix:
edit the CYAML_FIELD_SEQUENCE (and other macros) to declare the struct members in the right order

**Comment by CameronLovesCoffee** [comment]
After reading about designated initialisers, I see that this is a C vs C++ issue
Can you make the change so that it compiles in C++ as well as C?

**Comment by tlsa** [comment]
Should be fine on `main` now. Thanks for the report!
