### ISSUE TITLE
How to encode yaml files with string values that are within ''

### ISSUE THREAD

**Issue by vaishnaviv03** [tlsa/libcyaml#172]
Hi,

Is there any way we can encode a string value of a filed in the yaml file within '' (single quotes)? 
Something like this - 
header: {op: PHASE1, ref: FILE1, version: '1.0'}

Normal string encoding does not provide '' around the value, i tried to escape the quotes as well, but to no luck.

Requesting you to kindly help.

Thanks!
Vaishnavi

**Comment by tlsa** [comment]
Hi Vaishnavi,

> ```yaml
> header: {op: PHASE1, ref: FILE1, version: '1.0'}
> ```

Yes, that should just work, you can use `CYAML_INT`, `CYAML_UINT`, `CYAML_FLOAT`, or `CYAML_STRING` to load the `1.0` as a signed integer, unsigned integer, floating point value, or string respectively.  The single quotes will not matter.

Single quotes have the effect of ignoring escape sequences, so a `'\n'` would parse as a literal `\n`, but in double quotes it would be converted to a new line control character.
