### ISSUE TITLE
Build dynamic data and save to file

### ISSUE THREAD

**Issue by elecpower** [tlsa/libcyaml#177]
I'll preface this question with C is not my strong point but I know others who are if there is a solution. So apologies if this is a dumb question.
This has some similarities to #123. 
In my case I want to read a file to an input data struct, traverse the read data struct and copy the values to various memory variables and structs, manipulate the copied data, based on variable conditions construct an output data struct and then save to file.
An alterative situation is where there is no input data. The data is constructed in memory and then written.
A bit like having an read schema and its data, and a write schema and its data.
Thanks in advance

**Comment by tlsa** [comment]
So far as I understand the question, this is completely possible.

Could you give a short example of the data you want to load and save?

**Comment by elecpower** [comment]
I'll knock one up and post

**Comment by elecpower** [comment]
I looked at the planner example which reads, amends and writes.
So taking that example remove read and manipulate steps. Then using the plan_schema and an empty plan structure, load the plan struct (cyaml_load_file without the file parsing and leveraging in-built functions) and when finished call cyaml_save_file.
I hope this makes sense.

**Comment by elecpower** [comment]
Basically create the project.yaml file from code

**Comment by tlsa** [comment]
Yes you can do that.  There is absolutely no requirement that the data you save was originally created by a cyaml_load call.  So long as you write a schema that is correct for your data structure it will work.

**Comment by elecpower** [comment]
Thanks for your fast response.
Without completely pulling the code apart, my main concern was about potential null/invalid memory pointers between the schema and the data.

**Comment by tlsa** [comment]
Any members of your data structure that you want to save (i.e. ones described in your schema) must not be invalid pointers, they must point to the thing that the schema says they point to. Or they can be NULL if your schema allows them to have a NULL value (i.e. using `CYAML_FLAG_POINTER_NULL`, or `CYAML_FLAG_POINTER_NULL_STR`).  If your data has a NULL pointer but your schema doesn't permit NULL for that value, then the cyaml_save function will return `CYAML_ERR_INVALID_VALUE`.

**Comment by elecpower** [comment]
Thank you again for the tips
