### ISSUE TITLE
Invalid data on save of unchanged input data

### ISSUE THREAD

**Issue by elecpower** [tlsa/libcyaml#178]
Able to read the file successfully but writing the data unchanged fails. I assume it is my schema definition so some help would be appreciated. Attached are the source code, yaml file, debug output and cmake instructions
[code.txt](https://github.com/tlsa/libcyaml/files/7610688/code.txt)
[debug.txt](https://github.com/tlsa/libcyaml/files/7610689/debug.txt)
[yaml.txt](https://github.com/tlsa/libcyaml/files/7610690/yaml.txt)
[CMakeLists.txt](https://github.com/tlsa/libcyaml/files/7610691/CMakeLists.txt)

**Comment by tlsa** [comment]
Your arrays of models and categories are arrays of those structs, not arrays of pointers to structs in the data structure. So mappings (which are the sequence value type) should not have the pointer flag.

```diff
--- a/code.txt
+++ b/code.txt
@@ -33,7 +33,7 @@ static const cyaml_schema_field_t model_fields_schema[] = {
 };
 
 static const cyaml_schema_value_t model_schema = {
-       CYAML_VALUE_MAPPING(CYAML_FLAG_POINTER,
+       CYAML_VALUE_MAPPING(CYAML_FLAG_DEFAULT,
                        struct model, model_fields_schema),
 };
 
@@ -51,7 +51,7 @@ static const cyaml_schema_field_t category_fields_schema[] = {
 };
 
 static const cyaml_schema_value_t category_schema = {
-       CYAML_VALUE_MAPPING(CYAML_FLAG_POINTER | CYAML_FLAG_FLOW,
+       CYAML_VALUE_MAPPING(CYAML_FLAG_DEFAULT | CYAML_FLAG_FLOW,
                        struct category, category_fields_schema),
 };
```

**Comment by elecpower** [comment]
Thank you very much for your assistance and prompt attention. Cheers
