### ISSUE TITLE
Using cyaml on iOS

### ISSUE THREAD

**Issue by orassemusse** [tlsa/libcyaml#183]
Hello,
Using cyaml on iOS I have quite a hard time making it work.
I thought it could be a very valuable tool but I always get weird memory issues.
It might be my schemas which are not well defined.
Could you tell me what you think about it ?
Best regards,
Olivier
[base-theme.yaml.txt](https://github.com/tlsa/libcyaml/files/8153878/base-theme.yaml.txt)
[theme.h.txt](https://github.com/tlsa/libcyaml/files/8153881/theme.h.txt)

**Comment by tlsa** [comment]
You could avoid some extra allocations too. For example, for image regions:

```diff
diff --git a/theme.h.txt b/theme.h.txt
index efcf0ee..a7a84d6 100644
--- a/theme.h.txt
+++ b/theme.h.txt
@@ -30,7 +30,7 @@ static const cyaml_schema_value_t SRef_schema = {
 struct SImage
 {
     const char* image;
-    const int* region;
+    const int region[4];
 };
 
 static const cyaml_schema_value_t region_entry = {
@@ -43,7 +43,7 @@ static const cyaml_schema_field_t SImage_fields_schema[] = {
             struct SImage, image, 0, CYAML_UNLIMITED),
     
     CYAML_FIELD_SEQUENCE_FIXED(
-            "region", CYAML_FLAG_POINTER,
+            "region", CYAML_FLAG_DEFAULT,
             struct SImage, region, &region_entry, 4),
     
     CYAML_FIELD_END

```
