### ISSUE TITLE
add array value

### ISSUE THREAD

**Issue by macoomac** [tlsa/libcyaml#190]
project.yaml
-------------------
users:
  - name: abc
    list: ccccyy
  - name: uxy
    list: uuiisdfsf

---------------------

code
-------------------	
struct users_s
{	
    struct users_s *users;
    uint64_t users_count;
}

....
static const cyaml_schema_value_t top_schema = {		
CYAML_VALUE_MAPPING(CYAML_FLAG_DEFAULT,
.....

err = cyaml_load_file(argv[ARG_PATH_IN], &config,
		&top_schema, (cyaml_data_t **)&n, NULL);

question:
-----------------------
How to add or delete new users from the users array using code is as follows
name: testuser
list: readmetestuser

Where is the trial code?

**Comment by tlsa** [comment]
LibCYAML only does loading from YAML and saving to YAML.

If you want to modify the loaded data, `realloc` the users array to fit the extra entry, and increment `users_count`.

**Comment by macoomac** [comment]
> 

where  is sample code ?   
where url?
