### ISSUE TITLE
.mem_fn = cyaml_mem   Method or interface written to shared memory

### ISSUE THREAD

**Issue by macoomac** [tlsa/libcyaml#193]
static const cyaml_config_t config = {
	.log_level = CYAML_LOG_WARNING, /* Logging errors and warnings only. */
	.log_fn = cyaml_log,            /* Use the default logging function. */
	.mem_fn = cyaml_mem,            /* Use the default memory allocator. */
};

Replace cyaml_mem  Method or interface written to shared memory。

**Comment by tlsa** [comment]
I'm not sure what the question is. You can set mem_fn to your own custom allocation function.

**Comment by macoomac** [comment]
cyaml_ Mem uses malloc and realloc functions,
Whether cymal has encapsulated shm_open or shmget interface.

example：
void *cyaml_shm_mem(*ctx, void *ptr, size_t size); //shared memory function

**Comment by tlsa** [comment]
> cyaml_ Mem uses malloc and realloc functions

The **default implementation** of the allocation function, `cyaml_mem` uses realloc/free. You don't have to use `cyaml_mem`. You can use your own custom one by implementing this:

```c
/**
 * CYAML memory allocation / freeing function.
 *
 * Clients may implement this to handle memory allocation / freeing.
 *
 * \param[in] ctx    Client's private allocation context.
 * \param[in] ptr    Existing allocation to resize, or NULL.
 * \param[in] size   The new size for the allocation.  \note setting 0 must
 *                   be treated as free().
 * \return If `size == 0`, returns NULL.  If `size > 0`, returns NULL on failure,
 *         and any existing allocation is left untouched, or return non-NULL as
 *         the new allocation on success, and the original pointer becomes
 *         invalid.
 */
typedef void * (*cyaml_mem_fn_t)(
		void *ctx,
		void *ptr,
		size_t size);
```

And then make LibCYAML use your function by asigning it to mem_fn in the config:

```c
	.mem_fn = my_allocator,
```

> Whether cymal has encapsulated shm_open or shmget interface.

No, libcyaml doesn't use `shm_open` or `shmget` at all.
