### ISSUE TITLE
Do not detect invalid float values

### ISSUE THREAD

**Issue by ccoustet** [tlsa/libcyaml#195]
Due to errors in the data I try to read, I would expect a parsing error, but parsing just read the initial part of the number, up to the error.
The invalid double is "0.452*00E003", and cyaml__read_float_d parses it as 0.452.
As I don't have the whole picture I may be wrong, but it seems to me that testing if strtod() sets *end to '\0' could do the trick.
Maybe the same applies to other number types.
Thanks for your great work.

**Comment by tlsa** [comment]
Interesting, I'll have a look.

**Comment by tlsa** [comment]
Fixed now on the `main` branch. Thanks for the report.
