### ISSUE TITLE
How to use CYAML_FIELD_BITFIELDS in case of variables declared in structure

### ISSUE THREAD

**Issue by Anil9436** [tlsa/libcyaml#220]
I have one structure in that i have 8  variables in that 4 variables uses bitfields, when im trying to map the key with the values in the struct it says running sizeof operator on bitfields as one error, and another is attempt to take address of bit-field structure 
CYAML_FIELD_BITFIELD("aggregatorsource", CYAML_FLAG_DEFAULT, chainfilter, ucAgrSource, chainfilterbit_def, 1),
115:5: error: attempt to take address of bit-field structure member ‘ucAgrSource’
115 | CYAML_FIELD_BITFIELD("aggregatorsource", CYAML_FLAG_DEFAULT, chainfilter, ucAgrSource, chainfilterbit_def, 1),
15:5: error: ‘sizeof’ applied to a bit-field
115 | CYAML_FIELD_BITFIELD("aggregatorsource", CYAML_FLAG_DEFAULT, chainfilter, ucAgrSource, chainfilterbit_def, 1),
these are the errors of this

**Comment by tlsa** [comment]
This is untested, but I'd expect something like the following to at least compile:

Using a data structure like:

```c
struct my_struct {
	char *name;
	struct bits {
		unsigned bit0 : 1;
		unsigned bit1 : 1;
		unsigned bit2 : 1;
		unsigned bit3 : 1;
		unsigned bit4 : 4;
	} bits;
};
```

And a schema like:

```c
static const cyaml_bitdef_t bit_schema[] = {
	{
		.name = "bit0",
		.offset = 0,
		.bits = 1,
	},
	{
		.name = "bit1",
		.offset = 1,
		.bits = 1,
	},
	{
		.name = "bit2",
		.offset = 2,
		.bits = 1,
	},
	{
		.name = "bit3",
		.offset = 3,
		.bits = 1,
	},
	{
		.name = "bit4",
		.offset = 4,
		.bits = 4,
	},
};

static const struct cyaml_schema_field my_struct_schema[] = {
	CYAML_FIELD_STRING_PTR("name", CYAML_FLAG_POINTER,
			struct my_struct, name,
			0, CYAML_UNLIMITED),
	CYAML_FIELD_BITFIELD("bits", CYAML_FLAG_DEFAULT,
			struct my_struct, bits,
			bit_schema, CYAML_ARRAY_LEN(bit_schema)),
	CYAML_FIELD_END
};
```

Note that the actual placement of bits in a bitfield is undefined in the C spec, so you'd be relying on compiler behavior.

I always use the `CYAML_BITFIELD` with an unsigned integer type, rather than a C bitfield, and access the bits via shift and mask.

**Comment by Anil9436** [comment]
Thanks, It helped me. Previously i was trying by keeping my bit-field elements and also the non-bit field elements in the same structure so it didn't worked.
