### ISSUE TITLE
CMake File

### ISSUE THREAD

**Issue by SaiKiran-5** [tlsa/libcyaml#221]
Hi tlsa, 
I am using libcyaml for my project and we use cmake for building. I see there is no cmake file for this repo and it took some time for integrating libcyaml to my project.
So, is there any plan on writing cmake file for libcyaml or anyone is already working on it? If not **i like to contribute**.

Thanks.

**Comment by tlsa** [comment]
Hi @SaiKiran-5 

I don't want to change the buildsystem or maintain another one. Please see the discussion in https://github.com/tlsa/libcyaml/pull/174 for the reasons.

Please note that the LibCYAML buildsystem generates pkg-config files. I don't know the CMake equivalent but it can't be much more complicated than what you do in `make` to use an installed 3rd party library with a pkg-config file:

```make
CFLAGS += $(shell pkg-config libcyaml --cflags)
LDFLAGS += $(shell pkg-config libcyaml --libs)
```

Thank you for your interest in LibCYAML.
