### ISSUE TITLE
Build should use `_Static_assert` is `static_assert` is not defined

### ISSUE THREAD

**Issue by barracuda156** [tlsa/libcyaml#230]
This may not work with GCC, which uses `_Static_assert` instead:
```
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_libcyaml/libcyaml/work/compwrap/cc/opt/local/bin/gcc-mp-13 -I/opt/local/include -DVERSION_MAJOR=1 -DVERSION_MINOR=4 -DVERSION_PATCH=1 -DVERSION_DEVEL=0 -MMD -MP -Os -arch ppc -I include  -std=c11 -Wall -Wextra -pedantic -Wconversion -Wwrite-strings -Wcast-align -Wpointer-arith -Winit-self -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wundef -Wvla -Wdeclaration-after-statement -O2 -DNDEBUG -o build/release/planner examples/planner/main.c build/release/libcyaml.a -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -lyaml
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_libcyaml/libcyaml/work/compwrap/cc/opt/local/bin/gcc-mp-13 -I/opt/local/include -DVERSION_MAJOR=1 -DVERSION_MINOR=4 -DVERSION_PATCH=1 -DVERSION_DEVEL=0 -MMD -MP -Os -arch ppc -I include  -std=c11 -Wall -Wextra -pedantic -Wconversion -Wwrite-strings -Wcast-align -Wpointer-arith -Winit-self -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wundef -Wvla -Wdeclaration-after-statement -O2 -DNDEBUG -o build/release/numerical examples/numerical/main.c build/release/libcyaml.a -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -lyaml
Undefined symbols:
  "_static_assert", referenced from:
      _cyaml__free_value in free.o
      _cyaml__free_value in free.o
      _cyaml__data_handle_pointer in load.o
      _cyaml__data_handle_pointer in load.o
      _cyaml__write_value in save.o
      _cyaml__write_value in save.o
      _cyaml__write_mapping in save.o
      _cyaml__write_mapping in save.o
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make: *** [build/release/libcyaml.1.dylib] Error 1
make: *** Waiting for unfinished jobs....
Undefined symbols:
  "_static_assert", referenced from:
      _cyaml__free_value in libcyaml.a(free.o)
      _cyaml__free_value in libcyaml.a(free.o)
      _cyaml__data_handle_pointer in libcyaml.a(load.o)
      _cyaml__data_handle_pointer in libcyaml.a(load.o)
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make: *** [build/release/numerical] Error 1
Undefined symbols:
  "_static_assert", referenced from:
      _cyaml__free_value in libcyaml.a(free.o)
      _cyaml__free_value in libcyaml.a(free.o)
      _cyaml__write_value in libcyaml.a(save.o)
      _cyaml__write_value in libcyaml.a(save.o)
      _cyaml__write_mapping in libcyaml.a(save.o)
      _cyaml__write_mapping in libcyaml.a(save.o)
      _cyaml__data_handle_pointer in libcyaml.a(load.o)
      _cyaml__data_handle_pointer in libcyaml.a(load.o)
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make: *** [build/release/planner] Error 1
```

**Comment by tlsa** [comment]
What version of GCC are you using? I've never seen this.

C11 has `_Static_assert` as a keyword and `static_assert` as a convenience macro in `assert.h`.

This project is built as `-std=c11` and in all places that include `data.h`, `assert.h` is included before.

**Comment by barracuda156** [comment]
@tlsa Thank you for responding. The fix is borrowed from Python: https://github.com/python/cpython/blob/v3.12.1/Include/pymacro.h#L20-L24

I use gcc-13. This error shows up here and there, it is nothing new.

**Comment by tlsa** [comment]
> The fix is borrowed from Python: https://github.com/python/cpython/blob/v3.12.1/Include/pymacro.h#L20-L24

Okay, thanks for the context!

> I use gcc-13.

Me too. It seems to be more a libc issue.

> This error shows up here and there, it is nothing new.

From the comment in the Python code:

> ```c
> // gh-91782: On FreeBSD 12, if the _POSIX_C_SOURCE and _XOPEN_SOURCE macros are
> // defined, <sys/cdefs.h> disables C11 support and <assert.h> does not define
> // the static_assert() macro.
> // https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255290
> //
> // macOS <= 10.10 doesn't define static_assert in assert.h at all despite
> // having C11 compiler support.
> ```

Looking at that FreeBSD bug report, it looks like it was fixed in 2021.

And for MacOS it looks like 10.10 is about 10 years old, so that should be fixed too.

But I want this library to be buildable on old versions of those OSes too, so I'll revert https://github.com/tlsa/libcyaml/commit/a05e7db38073e5d1970e7797aafb46cfda668709. Thanks for reporting.

**Comment by tlsa** [comment]
About the FreeBSD one, I'm not defining `_POSIX_C_SOURCE` and `_XOPEN_SOURCE` for this project at all. It's pure ANSI C11. So I guess that's something that the platform does by default.

**Comment by barracuda156** [comment]
@tlsa Seems to work fine for me, thank you!

**Comment by barracuda156** [comment]
> Looking at that FreeBSD bug report, it looks like it was fixed in 2021.
> 
> And for MacOS it looks like 10.10 is about 10 years old, so that should be fixed too.

On PowerPC the last macOS we got is 10.6 :)
But some older Intel systems are also limited to earlier macOS versions (32-bit `i386` ones to 10.6 as well).

> But I want this library to be buildable on old versions of those OSes too, so I'll revert [a05e7db](https://github.com/tlsa/libcyaml/commit/a05e7db38073e5d1970e7797aafb46cfda668709). Thanks for reporting.

Great!

**Comment by tlsa** [comment]
Merged, thanks!
