### ISSUE TITLE
Integer overflow in `cyaml_sign_pad`

### ISSUE THREAD

**Issue by Rot127** [tlsa/libcyaml#246]
Our Coverity job discovered a possible integer overflow for the shift expression here:

https://github.com/tlsa/libcyaml/blob/c9956cbb50772ecc10fcf6a8ab210cce60e17567/src/save.c#L585-L596

If `size = 0` and `CHAR_BIT = 8` then `padding == 64` and `((uint64_t)1 << padding)` overflows to `0`. Due to this `raw` evaluates to `0xffffffffffffffff`. Independent what the actual value was before.

I just took a shallow look and don't have the time to make a PR with a test ready, unfortunately.
So please check if my thinking is flawed here.

**Comment by tlsa** [comment]
Hi @Rot127. It's a false positive. The size is something that comes from the `data_size` member in the user's value schema. Even if the user provides an invalid schema with `data_size` set to zero, the `cyaml_data_read` function will return an error (`CYAML_ERR_INVALID_DATA_SIZE`) which will be returned to the user, and `cyaml_sign_pad` will never be called with the invalid size.

**Comment by tlsa** [comment]
I'll see if I can rework the code to help Coverity understand.

**Comment by Rot127** [comment]
> Actually, are you using an old version of libcyaml? If you use [v1.4.2](https://github.com/tlsa/libcyaml/releases/tag/v1.4.2), the issue may go away.

Not yet.
But I can mark it as false positive for now. Thanks for checking it.
