### ISSUE TITLE
Error in "planner" example.

### ISSUE THREAD

**Issue by nikitinator** [tlsa/libcyaml#58]
In "plan" structure there is a pointer to structure date (start mapping). Therefore, to correctly parse it you should use CYAML_FIELD_MAPPING_PTR instead of CYAML_FIELD_MAPPING.

https://github.com/tlsa/libcyaml/blob/41e5d667c0a6b915c686afbd3c42b793f2ef4653/examples/planner/main.c#L330

**Comment by tlsa** [comment]
@nikitinator Fixed!  Thanks for the report!
