### ISSUE TITLE
Serializing field with NULL pointer value fails when flags = CYAML_FLAG_OPTIONAL | CYAML_FLAG_POINTER

### ISSUE THREAD

**Issue by JamesDunne** [tlsa/libcyaml#70]
It seems that `CYAML_FLAG_OPTIONAL` is not supported for serialization (save).

I would expect that serializing an optional *pointer* field would mean the field is skipped when `NULL`. For a scalar optional field, I'd expect fields to be skipped when their value is the default, e.g. `0`, `false`, or empty/NULL string.

What happens is the `save.c` code tries to dereference a `NULL` pointer and write its scalar value out which results in a `EXC_BAD_ACCESS` on Mac OS.

The error starts near `save.c:1044` in `cyaml__write_mapping`. The field should've been skipped just like the `field->value.type == CYAML_IGNORE` case.

**Comment by tlsa** [comment]
Thanks for the report!  I'll implement the optional flag for save tomorrow.

**Comment by JamesDunne** [comment]
Thanks! I appreciate your patience with my issue reports.

**Comment by tlsa** [comment]
Done, thanks!
