### ISSUE TITLE
Git repo versioning/tagging

### ISSUE THREAD

**Issue by ajd394** [tlsa/libcyaml#76]
Have you considered tagging the repo with versions? It would be helpful for projects that depend on this library.

**Comment by tlsa** [comment]
I was holding off until I was certain that I wasn't going to break the API/ABI.

Currently that means I need to finish off the support for aliases and anchors.  However, I don't have the time for that at the moment.

So I'm prepared to tag the current state of things as 0.0.1 and make no API/ABI stability guarantees until 1.0.0, if that's any use to you?  See #77.

**Comment by alex-tee** [comment]
+1
would help a lot if you had 0.x releases

**Comment by tlsa** [comment]
OK.  Will do when #78 is sorted.

**Comment by ajd394** [comment]
I think if you were adhering to [SemVer](https://semver.org/) you would probably want to start at 0.1.0 instead of 0.0.1.

**Comment by tlsa** [comment]
OK, I agree.  I'll try to make the 0.1.0 release this weekend.  Thanks for the pointer. :smiley_cat:

**Comment by tlsa** [comment]
Done: https://github.com/tlsa/libcyaml/releases
