### ISSUE TITLE
CYAML_FIELD_SEQUENCE_FIXED with statically defined array

### ISSUE THREAD

**Issue by cwbelknap** [tlsa/libcyaml#88]
Defining a structure with a static array and constructing the schema using CYAML_FIELD_SEQUENCE_FIXED results in incorrect data after parsing.

Consider the following structure and schema,
```C
struct test = {
    float foo;
    int bar[10];
}

static const cyaml_schema_value_t bar_schema = {
    CYAML_VALUE_INT(CYAML_FLAG_DEFAULT, int)
};

static const cyaml_schema_field_t test_fields_schema[] = {
    CYAML_FIELD_FLOAT("foo", CYAML_FLAG_OPTIONAL, struct test, foo),
    CYAML_FIELD_SEQUENCE_FIXED("bar", CYAML_FLAG_POINTER, struct test, bar, &bar_schema, 10),
    CYAML_FIELD_END
};

static const cyaml_schema_value_t test_schema = {
    CYAML_VALUE_MAPPING(CYAML_FLAG_POINTER, struct test, test_fields_schema)
};
```

when tested with the following file,
```YAML
foo: 123.4567
bar:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
```
results in the following values in the structure test,
```
foo: 123.4567
bar[0]: -503343168
bar[1]: 32767
bar[2]: 0
bar[3]: 0
bar[4]: 0
bar[5]: 0
bar[6]: 0
bar[7]: 0
bar[8]: 0
bar[9]: 0
```

**Comment by tlsa** [comment]
> ```c
>     CYAML_FIELD_SEQUENCE_FIXED("bar", CYAML_FLAG_POINTER, struct test, bar, &bar_schema, 10),
> ```

Since it's an array embedded in the struct, rather than a pointer to the array, the `CYAML_FLAG_POINTER` flag should not be set.  Try with `CYAML_FLAG_DEFAULT` instead.

**Comment by tlsa** [comment]
Is that working now?  :smile_cat:

**Comment by cwbelknap** [comment]
Yep, that fixed it. My understanding there was a little fuzzy I guess.
Thanks!

**Comment by tlsa** [comment]
You're welcome!

I'll look at whether I can improve the documentation later.

Thanks!
