### ISSUE TITLE
Cross compiling

### ISSUE THREAD

**Issue by cwbelknap** [tlsa/libcyaml#89]
Aside from setting CC, LD, and PREFIX, wow does one properly cross-compile the library?
Is there a env variable to define the location of includes (yaml.h) and libs (libyaml.so) if they are in non-standard locations, e.g. /usr/local/arm/include and /usr/local/arm/lib

**Comment by tlsa** [comment]
Try this:

```
make clean
CFLAGS="-I/usr/local/arm/include" LDFLAGS="-L/usr/local/arm/lib" make
```

**Comment by tlsa** [comment]
Closing, because I assume this is resolved.
