### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by alex-tee** [tlsa/libcyaml#97]
Bitfield support has been available for some time now. I have been using it and it works fine.

Can we get a new tag/release out please with the bitfield support? I want to package it and also I want to add a proper version dependency to my project. since i use the bitfield support, I would have something like `dependency ('cyaml', version: '>= 0.2')`

**Comment by lavigne958** [comment]
Hi I would be interested in a new release as well to better manage dependencies in our project. It would be awesome if you could make it. Thank in advance :wink:

**Comment by tlsa** [comment]
I've [released v1.0.0](https://github.com/tlsa/libcyaml/releases). :smile_cat:

**Comment by alex-tee** [comment]
thank you and congrats!! it's already very stable in my experience - i'm saving and loading huge YAMLs with it including bitfields and whatnot and it never caused a problem!
finally, i can remove cyaml from my tree and add a proper dependency to it :D

i'll send a package patch to Guix ASAP :)

**Comment by tlsa** [comment]
[Released v1.0.1](https://github.com/tlsa/libcyaml/releases). :smiley_cat:
